mm_symbols = ["JST_USDT", "DOT_USDT", "DIA_USDT", "COMP_USDT", "NULS_USDT", "BAL_USDT", "RSR_USDT",
    "UNI_USDT", "VTHO_USDT", "XRP_USDT", "LINK_USDT", "YFI_USDT", "UMA_USDT", "SNX_USDT", "ETH_USDT",
    "XRP_BTC", "XRP_ETH", "LTC_BTC", "LTC_ETH", "LTC_USDT", "LINK_BTC", "LINK_ETH", "EOS_USDT","NEO_USDT",
    "BTC_USDT", "ETH_BTC", "EOS_BTC", "EOS_ETH", "FIL_USDT", "KSM_USDT","OKB_USDT","HT_USDT","DGB_BTC",
    "NEO_BTC", "NEO_ETH",  "XLM_BTC", "XLM_ETH", "XLM_USDT","BMX_BTC", "BMX_USDT","BSV_BTC","SUSHI_USDT",
    "ZIL_BTC", "ZIL_ETH", "ZRX_BTC", "ZRX_ETH", "VET_BTC", "VET_ETH","MKR_ETH", "MKR_BTC", "KAN_ETH",
    "KAN_BTC","HYDRO_BTC", "HYDRO_ETH","GRIN_USDT","ABT_ETH", "ABT_BTC","BTM_BTC", "BTM_ETH"
    "VET_USDT", "OMG_BTC", "IOST_BTC", "CRO_USDT", "CRO_BTC","BHD_USDT","IOST_ETH","OMG_ETH",
    "AE_ETH", "AE_BTC", "GNT_ETH", "GNT_BTC", "ONT_BTC", "ONT_ETH","BTT_BTC","GUSD_USDT","OM_USDT",
    "TUSD_USDT", "PAX_USDT", "TRX_USDT", "TRX_BTC", "BCH_BTC", "BCH_USDT","NULS_USDT","CEL_ETH",
    "TRX_ETH", "ZEC_ETH", "USDC_USDT","ZEC_USDT","ZEC_BTC","WNXM_USDT","RFUEL_USDT","WOO_USDT",
    "BTT_USDT", "BNB_USDT", "BNB_BTC", "BNB_ETH", "QTUM_USDT", "GRT_USDT","AAVE_USDT","LON_USDT",
    "QTUM_BTC", "QTUM_ETH", "WAVES_ETH", "WAVES_USDT", "WAVES_BTC","1INCH_USDT","BSV_USDT","POLS_USDT",
    "BTC_PAX", "BTC_USDC","BMX_ETH",
    "ALGO_USDT", "ALGO_BTC", "ATOM_BTC", "ATOM_USDT",
    "DASH_USDT", "DASH_BTC", "DASH_ETH",
    "BAT_BTC", "BAT_ETH", "BAT_USDT", "MATIC_BTC", "MATIC_USDT", "REP_BTC", "REP_ETH",
    "ETC_BTC", "ETC_ETH", "ETC_USDT", "LOOM_BTC", "LOOM_ETH", "HOT_ETH", "HOT_USDT"
]
                
ty_symbols = ["APL_BTC", "APL_ETH", "APL_USDT", "BXTB_USDT", "ERSDL_ETH", "HEX_BTC", "$KING_USDT", 
    "$KING_BTC", "QRX_BTC", "QRX_USDT", "SG_BTC", "SG_USDT", "SHR_BTC", "WINR_USDT", "WTK_USDT",
    "VRA_USDT", "XTP_BTC", "ZNC_USDT"
]

