binance_symbols = [
    "BTC_USDT", "ETH_BTC", "ETH_USDT", "EOS_BTC", "EOS_ETH", "EOS_USDT",
    "NEO_BTC", "NEO_ETH", "NEO_USDT", "XLM_BTC", "XLM_ETH", "XLM_USDT",
    "ZIL_BTC", "ZIL_ETH", "ZRX_BTC", "ZRX_ETH", "VET_BTC", "VET_ETH",
    "VET_USDT", "OMG_BTC", "IOST_BTC", "XRP_BTC", "XRP_ETH", "XRP_USDT",
    "AE_ETH", "AE_BTC", "GNT_ETH", "GNT_BTC", "GXC_ETH", "GXC_BTC", "JST_USDT",
    "TUSD_USDT", "PAX_USDT", "TRX_USDT", "TRX_BTC", "BCH_BTC", "BCH_USDT",
    "TRX_ETH", "ZEC_ETH", "USDC_USDT", "LTC_USDT", "LTC_BTC", "LTC_ETH",
    "BTT_USDT", "BNB_USDT", "BNB_BTC", "BNB_ETH", "QTUM_USDT", "NULS_USDT",
    "QTUM_BTC", "QTUM_ETH", "WAVES_ETH", "WAVES_USDT", "WAVES_BTC",
    "BTC_PAX", "ETH_PAX", "XRP_PAX", "BCH_PAX", "LTC_PAX", "EOS_PAX",
    "XLM_PAX", "BTC_USDC", "ETH_USDC", "XRP_USDC", "BCH_USDC", "LTC_USDC",
    "EOS_USDC", "XLM_USDC", "BTC_TUSD", "ETH_TUSD", "XRP_TUSD", "BCH_TUSD",
    "LTC_TUSD", "EOS_TUSD", "XLM_TUSD", "ALGO_USDT", "ALGO_BTC", "ATOM_BTC", "ATOM_USDT",
    "DASH_USDT", "DASH_BTC", "DASH_ETH", "LINK_BTC", "LINK_ETH", "LINK_USDT",
    "BAT_BTC", "BAT_ETH", "BAT_USDT", "MATIC_BTC", "MATIC_USDT", "REP_BTC", "REP_ETH",
    "ETC_BTC", "ETC_ETH", "ETC_USDT", "LOOM_BTC", "LOOM_ETH", "HOT_ETH", "HOT_USDT"
]

huobi_symbols = [
    "BTC_USDT", "ETH_BTC", "ETH_USDT", "EOS_BTC", "EOS_ETH", "EOS_USDT",
    "NEO_BTC", "NEO_ETH", "NEO_USDT", "XLM_BTC", "XLM_ETH", "XLM_USDT", "JST_USDT",
    "ZIL_BTC", "ZIL_ETH", "ZRX_BTC", "ZRX_ETH", "VET_BTC", "VET_ETH", "VET_USDT",
    "XRP_BTC", "XRP_ETH", "XRP_USDT", "BCH_BTC", "BCH_USDT", "OMG_ETH", "OMG_BTC",
    "IOST_ETH", "ABT_ETH", "ABT_BTC", "KAN_BTC", "KAN_ETH", "BTT_ETH", "AE_BTC", "AE_ETH",
    "GXC_ETH", "GXC_BTC", "BCH_USDT", "BSV_USDT", "BTT_USDT", "BTT_BTC","ETC_BTC", "ETC_ETH", "ETC_USDT",
    "HT_USDT", "HT_BTC", "HT_ETH","ONT_USDT", "ONT_BTC", "ONT_ETH", "BHD_BTC", "BHD_ETH","BHD_USDT",
    "LINK_BTC", "LINK_ETH", "LINK_USDT", "BAT_BTC", "BAT_ETH", "BAT_USDT", "CRO_USDT", "CRO_BTC",
    "ALGO_USDT", "ALGO_BTC", "NULS_USDT"
]

okex_symbols = [
    "BTC_USDT", "ETH_BTC", "ETH_USDT", "EOS_BTC", "EOS_ETH", "EOS_USDT",
    "NEO_BTC", "NEO_ETH", "NEO_USDT", "XLM_BTC", "XLM_ETH", "XLM_USDT",
    "OMG_USDT", "ZIL_BTC", "ZIL_ETH", "ZRX_BTC", "ZRX_ETH", "XRP_BTC",
    "XRP_ETH", "XRP_USDT", "BCH_BTC", "BCH_USDT", "GUSD_USDT", "MKR_BTC",
    "MKR_ETH", "TUSD_USDT", "USDC_USDT", "OKB_USDT", "OKB_BTC", "OKB_ETH",
    "QTUM_ETH", "QTUM_BTC", "QTUM_USDT", "PAX_USDT", "LTC_USDT", "LTC_BTC",
    "LTC_ETH", "TRX_USDT", "TRX_BTC", "TRX_ETH", "BTM_BTC", "BTM_ETH","ONT_USDT",
    "ONT_BTC", "ONT_ETH", "DASH_USDT", "DASH_BTC", "DASH_ETH", "LINK_BTC",
    "LINK_ETH", "LINK_USDT", "DGB_BTC", "BTT_BTC", "BTT_USDT", "JST_USDT"
]

wootrade_symbols = []